#ifndef DISPLAY_MODE_H
#define DISPLAY_MODE_H

#define DISPLAY_WIDTH 320
#define DISPLAY_HEIGHT 240
#define BYTES_PER_PIXEL 3
#define DISPLAY_TOTAL_PIXELS (DISPLAY_WIDTH * DISPLAY_HEIGHT)
#define DISPLAY_TOTAL_BYTES (DISPLAY_TOTAL_PIXELS * BYTES_PER_PIXEL)
#define DISPLAY_BYTES_PER_ROW (DISPLAY_WIDTH * BYTES_PER_PIXEL)

enum DisplayMode {
    DISPLAY_MODE_OFF = 0,
    DISPLAY_MODE_IMAGE = 1,
    DISPLAY_MODE_ANIMATION = 2,
    DISPLAY_MODE_DISTANCE = 3
};

#endif
